
load("./results_model_calibration/COVID-19Piemonte-calibration.RData")

calibration_optim_trace <-read.csv("./results_model_calibration/COVID-19Piemonte-calibration_optim-trace.csv",sep = "")


# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./results_model_calibration/",
                     pattern = ".trace")

id.traces<-calibration_optim_trace$id[which.min(calibration_optim_trace$distance)]


paste(calibration_optim_trace[id.traces,-c(1:2)],collapse = ",")
unlist(calibration_optim_trace[id.traces,-c(1:2)] )->optim
